name: ci-cd-debug-env
on: [workflow_dispatch]

jobs:
  run-terminal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup session
        uses: mxschmitt/action-tmate@v2  
        timeout-minutes: 20              
